
namespace OneStopHelper.Model
{
    public class CollegeDataUSYearly_Scorecard
    {
        public int Year { get; set; }
        public double? ADM_RATE { get; set; }
        public double? ADM_RATE_ALL { get; set; }
        public double? SATVR25 { get; set; }
        public double? SATVR75 { get; set; }
        public double? SATMT25 { get; set; }
        public double? SATMT75 { get; set; }
        public double? SATWR25 { get; set; }
        public double? SATWR75 { get; set; }
        public double? SATVRMID { get; set; }
        public double? SATMTMID { get; set; }
        public double? SATWRMID { get; set; }
        public double? ACTCM25 { get; set; }
        public double? ACTCM75 { get; set; }
        public double? ACTEN25 { get; set; }
        public double? ACTEN75 { get; set; }
        public double? ACTMT25 { get; set; }
        public double? ACTMT75 { get; set; }
        public double? ACTWR25 { get; set; }
        public double? ACTWR75 { get; set; }
        public double? ACTCMMID { get; set; }
        public double? ACTENMID { get; set; }
        public double? ACTMTMID { get; set; }
        public double? ACTWRMID { get; set; }
        public double? SAT_AVG { get; set; }
        public double? UGDS { get; set; }
        public double? UGDS_WHITE { get; set; }
        public double? UGDS_BLACK { get; set; }
        public double? UGDS_HISP { get; set; }
        public double? UGDS_ASIAN { get; set; }
        public double? UGDS_AIAN { get; set; }
        public double? UGDS_NHPI { get; set; }
        public double? UGDS_2MOR { get; set; }
        public double? UGDS_NRA { get; set; }
        public double? UGDS_UNKN { get; set; }
        public double? UGDS_WHITENH { get; set; }
        public double? UGDS_BLACKNH { get; set; }
        public double? UGDS_API { get; set; }
        public double? NPT4_PUB { get; set; }
        public double? NPT4_PRIV { get; set; }
        public double? NPT41_PUB { get; set; }
        public double? NPT42_PUB { get; set; }
        public double? NPT43_PUB { get; set; }
        public double? NPT44_PUB { get; set; }
        public double? NPT45_PUB { get; set; }
        public double? NPT41_PRIV { get; set; }
        public double? NPT42_PRIV { get; set; }
        public double? NPT43_PRIV { get; set; }
        public double? NPT44_PRIV { get; set; }
        public double? NPT45_PRIV { get; set; }
        public double? NUM4_PUB { get; set; }
        public double? NUM4_PRIV { get; set; }
        public double? NUM41_PUB { get; set; }
        public double? NUM42_PUB { get; set; }
        public double? NUM43_PUB { get; set; }
        public double? NUM44_PUB { get; set; }
        public double? NUM45_PUB { get; set; }
        public double? NUM41_PRIV { get; set; }
        public double? NUM42_PRIV { get; set; }
        public double? NUM43_PRIV { get; set; }
        public double? NUM44_PRIV { get; set; }
        public double? NUM45_PRIV { get; set; }
        public double? COSTT4_A { get; set; }
        public double? COSTT4_P { get; set; }
        public double? TUITIONFEE_IN { get; set; }
        public double? TUITIONFEE_OUT { get; set; }
        public double? FEMALE { get; set; }
        public double? MARRIED { get; set; }
        public double? DEPENDENT { get; set; }
        public double? VETERAN { get; set; }
        public double? FIRST_GEN { get; set; }
        public double? FAMINC { get; set; }
        public double? MD_FAMINC { get; set; }
        public double? MEDIAN_HH_INC { get; set; }
        public double? POVERTY_RATE { get; set; }
        public double? UNEMP_RATE { get; set; }
        public double? GRAD_DEBT_MDN_SUPP { get; set; }
        public double? UGDS_MEN { get; set; }
        public double? UGDS_WOMEN { get; set; }
        public double? GRADS { get; set; }
        public double? COUNT_NWNE_P10 { get; set; }
        public double? COUNT_WNE_P10 { get; set; }
        public double? MN_EARN_WNE_P10 { get; set; }
        public double? MD_EARN_WNE_P10 { get; set; }
        public double? COUNT_NWNE_P6 { get; set; }
        public double? COUNT_WNE_P6 { get; set; }
        public double? MN_EARN_WNE_P6 { get; set; }
        public double? MD_EARN_WNE_P6 { get; set; }
        public double? COUNT_NWNE_P8 { get; set; }
        public double? COUNT_WNE_P8 { get; set; }
        public double? MN_EARN_WNE_P8 { get; set; }
        public double? MD_EARN_WNE_P8 { get; set; }

    }
}
