using Newtonsoft.Json;

namespace OneStopHelper.Model
{
    public class IPEDS_ICAY
    {
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }
        public string UNITID { get; set; }
        public double year { get; set; }
        public double? TUITION1 { get; set; }
        public double? FEE1 { get; set; }
        public double? HRCHG1 { get; set; }
        public double? TUITION2 { get; set; }
        public double? FEE2 { get; set; }
        public double? HRCHG2 { get; set; }
        public double? TUITION3 { get; set; }
        public double? FEE3 { get; set; }
        public double? HRCHG3 { get; set; }
        public double? TUITION5 { get; set; }
        public double? FEE5 { get; set; }
        public double? HRCHG5 { get; set; }
        public double? TUITION6 { get; set; }
        public double? FEE6 { get; set; }
        public double? HRCHG6 { get; set; }
        public double? TUITION7 { get; set; }
        public double? FEE7 { get; set; }
        public double? HRCHG7 { get; set; }
        public double? ISPROF1 { get; set; }
        public double? ISPFEE1 { get; set; }
        public double? OSPROF1 { get; set; }
        public double? OSPFEE1 { get; set; }
        public double? ISPROF2 { get; set; }
        public double? ISPFEE2 { get; set; }
        public double? OSPROF2 { get; set; }
        public double? OSPFEE2 { get; set; }
        public double? ISPROF3 { get; set; }
        public double? ISPFEE3 { get; set; }
        public double? OSPROF3 { get; set; }
        public double? OSPFEE3 { get; set; }
        public double? ISPROF4 { get; set; }
        public double? ISPFEE4 { get; set; }
        public double? OSPROF4 { get; set; }
        public double? OSPFEE4 { get; set; }
        public double? ISPROF5 { get; set; }
        public double? ISPFEE5 { get; set; }
        public double? OSPROF5 { get; set; }
        public double? OSPFEE5 { get; set; }
        public double? ISPROF6 { get; set; }
        public double? ISPFEE6 { get; set; }
        public double? OSPROF6 { get; set; }
        public double? OSPFEE6 { get; set; }
        public double? ISPROF7 { get; set; }
        public double? ISPFEE7 { get; set; }
        public double? OSPROF7 { get; set; }
        public double? OSPFEE7 { get; set; }
        public double? ISPROF8 { get; set; }
        public double? ISPFEE8 { get; set; }
        public double? OSPROF8 { get; set; }
        public double? OSPFEE8 { get; set; }
        public double? ISPROF9 { get; set; }
        public double? ISPFEE9 { get; set; }
        public double? OSPROF9 { get; set; }
        public double? OSPFEE9 { get; set; }
        public double? CHG1AT0 { get; set; }
        public double? CHG1AF0 { get; set; }
        public double? CHG1AY0 { get; set; }
        public double? CHG1AT1 { get; set; }
        public double? CHG1AF1 { get; set; }
        public double? CHG1AY1 { get; set; }
        public double? CHG1AT2 { get; set; }
        public double? CHG1AF2 { get; set; }
        public double? CHG1AY2 { get; set; }
        public double? CHG1AT3 { get; set; }
        public double? CHG1AF3 { get; set; }
        public double? CHG1AY3 { get; set; }
        public double? CHG1TGTD { get; set; }
        public double? CHG1FGTD { get; set; }
        public double? CHG2AT0 { get; set; }
        public double? CHG2AF0 { get; set; }
        public double? CHG2AY0 { get; set; }
        public double? CHG2AT1 { get; set; }
        public double? CHG2AF1 { get; set; }
        public double? CHG2AY1 { get; set; }
        public double? CHG2AT2 { get; set; }
        public double? CHG2AF2 { get; set; }
        public double? CHG2AY2 { get; set; }
        public double? CHG2AT3 { get; set; }
        public double? CHG2AF3 { get; set; }
        public double? CHG2AY3 { get; set; }
        public double? CHG2TGTD { get; set; }
        public double? CHG2FGTD { get; set; }
        public double? CHG3AT0 { get; set; }
        public double? CHG3AF0 { get; set; }
        public double? CHG3AY0 { get; set; }
        public double? CHG3AT1 { get; set; }
        public double? CHG3AF1 { get; set; }
        public double? CHG3AY1 { get; set; }
        public double? CHG3AT2 { get; set; }
        public double? CHG3AF2 { get; set; }
        public double? CHG3AY2 { get; set; }
        public double? CHG3AT3 { get; set; }
        public double? CHG3AF3 { get; set; }
        public double? CHG3AY3 { get; set; }
        public double? CHG3TGTD { get; set; }
        public double? CHG3FGTD { get; set; }
        public double? CHG4AY0 { get; set; }
        public double? CHG4AY1 { get; set; }
        public double? CHG4AY2 { get; set; }
        public double? CHG4AY3 { get; set; }
        public double? CHG5AY0 { get; set; }
        public double? CHG5AY1 { get; set; }
        public double? CHG5AY2 { get; set; }
        public double? CHG5AY3 { get; set; }
        public double? CHG6AY0 { get; set; }
        public double? CHG6AY1 { get; set; }
        public double? CHG6AY2 { get; set; }
        public double? CHG6AY3 { get; set; }
        public double? CHG7AY0 { get; set; }
        public double? CHG7AY1 { get; set; }
        public double? CHG7AY2 { get; set; }
        public double? CHG7AY3 { get; set; }
        public double? CHG8AY0 { get; set; }
        public double? CHG8AY1 { get; set; }
        public double? CHG8AY2 { get; set; }
        public double? CHG8AY3 { get; set; }
        public double? CHG9AY0 { get; set; }
        public double? CHG9AY1 { get; set; }
        public double? CHG9AY2 { get; set; }
        public double? CHG9AY3 { get; set; }

        
    }
}
